
services:
  api: 
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ah_petsaddopt_web
    ports:
        - "8021:8021"
  
  db:
    image: postgres:latest
    environment:
      - DB_NAME=Centro_animals
      - DB_USER=base1
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=7012
    networks:
      - ag
networks:
  ag: 
    external : true

  
