version: '3.8'

services:
  api: 
    build: ./api
    container_name: ah_petsaddopt_web
    ports:
      - "7011 : 8000"
  
    environment:
      - DB_NAME=Centro_animals
      - DB_USER=base1
      - DB_PASSWORD=123456
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - ag
networks:
  ag: 
    external : true

  